<?php require_once __DIR__.'/functions.php'; $pageTitle = $pageTitle ?? 'CineVerse'; ?>
<!doctype html><html lang="en" data-bs-theme="dark"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?=e($pageTitle)?> | CineVerse</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet"><link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"><link href="/movie-booking/assets/css/style.css?v=2" rel="stylesheet">
</head><body>
<div id="loader"><i class="fa-solid fa-film fa-spin"></i></div>
<nav class="navbar navbar-expand-lg navbar-dark sticky-top glass"><div class="container"><a class="navbar-brand fw-bold" href="/movie-booking/index.php"><i class="fa-solid fa-clapperboard text-warning"></i> CINEVERSE</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div id="nav" class="collapse navbar-collapse"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-2"><li class="nav-item"><a class="nav-link" href="/movie-booking/index.php#movies">Movies</a></li><li class="nav-item"><a class="nav-link" href="/movie-booking/index.php#upcoming">Coming soon</a></li><?php if(is_logged_in()): ?><li class="nav-item"><a class="nav-link" href="/movie-booking/user/dashboard.php">My bookings</a></li><li class="nav-item"><a class="btn btn-sm btn-outline-light" href="/movie-booking/logout.php">Logout</a></li><?php else: ?><li class="nav-item"><a class="nav-link" href="/movie-booking/login.php">Login</a></li><li class="nav-item"><a class="btn btn-sm btn-gradient" href="/movie-booking/register.php">Join now</a></li><?php endif ?></ul></div></div></nav>
<main><?php if($flashMessage=flash('error')): ?><div class="container pt-3"><div class="alert alert-danger"><?=e($flashMessage)?></div></div><?php endif ?><?php if($flashMessage=flash('success')): ?><div class="container pt-3"><div class="alert alert-success"><?=e($flashMessage)?></div></div><?php endif ?>
