CREATE DATABASE IF NOT EXISTS movie_booking CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE movie_booking;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS notifications,favorites,reviews,payments,booked_seats,bookings,shows,screens,theaters,movies,users,admin;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE admin(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,phone VARCHAR(30),status ENUM('active','blocked') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE movies(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,poster VARCHAR(255),banner VARCHAR(255),trailer_url VARCHAR(255),cast_members TEXT,director VARCHAR(150),language VARCHAR(80),duration VARCHAR(40),genre VARCHAR(120),release_date DATE,description TEXT,ticket_price DECIMAL(10,2) DEFAULT 250,status ENUM('now_showing','upcoming') DEFAULT 'now_showing',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(status),INDEX(release_date)) ENGINE=InnoDB;
CREATE TABLE theaters(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,address VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE screens(id INT AUTO_INCREMENT PRIMARY KEY,theater_id INT NOT NULL,name VARCHAR(80) NOT NULL,FOREIGN KEY(theater_id) REFERENCES theaters(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE shows(id INT AUTO_INCREMENT PRIMARY KEY,movie_id INT NOT NULL,screen_id INT NOT NULL,show_date DATE NOT NULL,show_time TIME NOT NULL,ticket_price DECIMAL(10,2) NOT NULL,FOREIGN KEY(movie_id) REFERENCES movies(id) ON DELETE CASCADE,FOREIGN KEY(screen_id) REFERENCES screens(id) ON DELETE CASCADE,INDEX(movie_id,show_date)) ENGINE=InnoDB;
CREATE TABLE bookings(id INT AUTO_INCREMENT PRIMARY KEY,booking_code VARCHAR(24) UNIQUE NOT NULL,user_id INT NOT NULL,show_id INT NOT NULL,total_amount DECIMAL(10,2) NOT NULL,status ENUM('confirmed','cancelled') DEFAULT 'confirmed',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(show_id) REFERENCES shows(id) ON DELETE CASCADE,INDEX(user_id),INDEX(show_id)) ENGINE=InnoDB;
CREATE TABLE booked_seats(id INT AUTO_INCREMENT PRIMARY KEY,booking_id INT NOT NULL,show_id INT NOT NULL,seat_number VARCHAR(5) NOT NULL,FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE,FOREIGN KEY(show_id) REFERENCES shows(id) ON DELETE CASCADE,UNIQUE KEY unique_show_seat(show_id,seat_number)) ENGINE=InnoDB;
CREATE TABLE payments(id INT AUTO_INCREMENT PRIMARY KEY,booking_id INT NOT NULL,amount DECIMAL(10,2) NOT NULL,method VARCHAR(50) DEFAULT 'Counter',status ENUM('paid','pending','refunded') DEFAULT 'paid',paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE reviews(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,movie_id INT NOT NULL,rating TINYINT NOT NULL,review TEXT,approved TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(movie_id) REFERENCES movies(id) ON DELETE CASCADE,INDEX(movie_id,approved)) ENGINE=InnoDB;
CREATE TABLE favorites(user_id INT NOT NULL,movie_id INT NOT NULL,PRIMARY KEY(user_id,movie_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(movie_id) REFERENCES movies(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE notifications(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,movie_id INT NOT NULL,message VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(movie_id) REFERENCES movies(id) ON DELETE CASCADE,UNIQUE KEY notify_once(user_id,movie_id)) ENGINE=InnoDB;
INSERT INTO admin(name,email,password) VALUES('Administrator','admin@cineverse.test','$2y$10$Yxm6iSA4LNLP6YDOdYxG9.Cw/04NWNXw2y66nmfcPi.EwL5BlsDqK');
INSERT INTO movies(title,poster,trailer_url,cast_members,director,language,duration,genre,release_date,description,ticket_price,status) VALUES
('Avatar: Fire and Ash','assets/images/posters/avatar-fire-and-ash.svg','https://www.youtube.com/embed/d9MyW72ELq0','Sam Worthington, Zoe Saldaña','James Cameron','English','3h 12m','Sci-Fi, Adventure','2025-12-19','Return to Pandora for an epic new chapter.',350,'now_showing'),
('Superman','assets/images/posters/superman.svg','https://www.youtube.com/embed/uhUht6vAsMY','David Corenswet, Rachel Brosnahan','James Gunn','English','2h 9m','Action, Fantasy','2025-07-11','A hopeful hero learns to balance heritage and humanity.',300,'now_showing'),
('Jurassic World Rebirth','assets/images/posters/jurassic-world-rebirth.svg','https://www.youtube.com/embed/jan5CFWs9ic','Scarlett Johansson, Mahershala Ali','Gareth Edwards','English','2h 14m','Action, Adventure','2025-07-02','A dangerous expedition enters a forgotten island.',320,'now_showing'),
('Mission: Impossible – The Final Reckoning','assets/images/posters/mission-impossible-final-reckoning.svg','https://www.youtube.com/embed/fsQgc9pCyDU','Tom Cruise, Hayley Atwell','Christopher McQuarrie','English','2h 49m','Action, Thriller','2025-05-23','Ethan Hunt faces his most impossible mission.',340,'now_showing'),
('Fantastic Four','assets/images/posters/fantastic-four.svg','https://www.youtube.com/embed/AzMo-FgRp64','Pedro Pascal, Vanessa Kirby','Matt Shakman','English','1h 55m','Action, Sci-Fi','2025-07-25','Marvel’s first family protects a retro-future world.',300,'now_showing'),
('F1','assets/images/posters/f1.svg','https://www.youtube.com/embed/8yh9BPUBbbQ','Brad Pitt, Damson Idris','Joseph Kosinski','English','2h 35m','Drama, Sport','2025-06-27','A veteran driver returns to Formula One glory.',280,'now_showing'),
('Ballerina','assets/images/posters/ballerina.svg','https://www.youtube.com/embed/0FSwsrFpkbw','Ana de Armas, Keanu Reeves','Len Wiseman','English','2h 5m','Action, Thriller','2025-06-06','An assassin seeks revenge in the John Wick world.',290,'now_showing'),
('Elio','assets/images/posters/elio.svg','https://www.youtube.com/embed/2bYfs1Z4E1U','Yonas Kibreab, Zoe Saldaña','Madeline Sharafian','English','1h 39m','Animation, Family','2025-06-20','A space fanatic becomes Earth’s accidental ambassador.',220,'now_showing'),
('How to Train Your Dragon','assets/images/posters/how-to-train-your-dragon.svg','https://www.youtube.com/embed/22w7z_lT6YM','Mason Thames, Nico Parker','Dean DeBlois','English','2h 5m','Fantasy, Adventure','2025-06-13','A Viking and dragon forge an unlikely friendship.',280,'now_showing'),
('The Bad Guys 2','assets/images/posters/the-bad-guys-2.svg','https://www.youtube.com/embed/bFSN6amz-yY','Sam Rockwell, Awkwafina','Pierre Perifel','English','1h 44m','Animation, Comedy','2025-08-01','The reformed crew is pulled into one last heist.',220,'upcoming');
INSERT INTO theaters(name,address) VALUES('CineVerse IMAX','Central Plaza, Main Street'); INSERT INTO screens(theater_id,name) VALUES(1,'Screen 1'),(1,'Screen 2');
INSERT INTO shows(movie_id,screen_id,show_date,show_time,ticket_price) SELECT id,1,CURDATE()+INTERVAL 1 DAY,'18:30:00',ticket_price FROM movies WHERE status='now_showing';
